export const DOCUMENT_REPOSITORY = Symbol("DOCUMENT_REPOSITORY");
export const DOCUMENT_INGESTION_QUEUE = Symbol("DOCUMENT_INGESTION_QUEUE");
export const EMBEDDING_PROVIDER = Symbol("EMBEDDING_PROVIDER");
export const LLM_PROVIDER = Symbol("LLM_PROVIDER");
export const VECTOR_STORE = Symbol("VECTOR_STORE");
