export const GITHUB_CONNECTION_REPOSITORY = Symbol(
  "GITHUB_CONNECTION_REPOSITORY"
);

export const GITHUB_INSTALLATION_REPOSITORY = Symbol(
  "GITHUB_INSTALLATION_REPOSITORY"
);

export const GITHUB_ACTION_REVIEW_REPOSITORY = Symbol(
  "GITHUB_ACTION_REVIEW_REPOSITORY"
);
